name: Build and Release
permissions: write-all

on:
  push:
    branches:
      - main 


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [stable, longterm, testing, dev]
        exclude:
          - channel: dev
          - channel: longterm
          - channel: testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install packages into building machine
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip qemu-utils rsync gdisk dosfstools parted genisoimage zip
      - name: Set version if release channel name
        id: get-version
        if: ${{ (github.event_name != 'workflow_dispatch' && matrix.channel != 'custom') }}
        run: |
          ROS7=`curl https://download.mikrotik.com/routeros/NEWESTa7.${{matrix.channel}} | awk '{print $1}'`
          echo "ROSVER=$ROS7" >> $GITHUB_ENV
      - name: Print versions for debugging
        run: |
          echo "Build using $ROSVER"  
      - name: Run script to download and modify the CHR images
        run: sudo bash build.bash $ROSVER
      - name: Upload created image files as artifacts of build
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: ./chr*
